# Generated by Django 5.0 on 2024-02-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='TaskItem',
        ),
    ]
