# Generated by Django 5.0 on 2024-02-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_cartitem_taskitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskitem',
            old_name='cart',
            new_name='job',
        ),
    ]
